server:
  port: 9191

spring:
  zipkin:    base-url: http://localhost:9411/
      application:    name: PAYMENT-SERVICE
    
logging:  file:    name: C:\Users\manju\Desktop\microserviceloggers/shoppingservice.log
